In [3]:
import random
from faker import Faker
import numpy as np
import pandas as pd
from datetime import datetime, timedelta

In [1]:
# Ruta relativa
ruta_csv_users = "../data/users_login/users.csv"

In [4]:
# Leemos el DataFrame
df = pd.read_csv(ruta_csv_users)
df

fecha_registro              nombre  user_id sexo fecha_nacimiento     cp   
0       24-04-2023          Lynn Moore   655346    M       27-09-1954  28023  \
1       02-06-2023     Lisa Valenzuela   279526    H       28-10-1934  28037   
2       20-03-2023    Matthew Marshall   797457    H       17-09-1946  28035   
3       03-02-2023         Ryan Rogers   803906    H       13-06-1936  28026   
4       25-01-2023     Destiny Shaffer   314182    H       27-12-1961  28024   
..             ...                 ...      ...  ...              ...    ...   
495     01-03-2023         Hannah Luna   204336    H       14-08-2002  28083   
496     26-02-2023  Christopher Powell   802317    M       12-08-1930  28054   
497     02-02-2023          Sara Morse   549513    M       22-07-1924  28053   
498     04-02-2023     Dr. Peter Curry   292753    M       16-05-1942  28026   
499     12-03-2023       Dwayne Gordon   103476    M       01-02-1995  28071   

     n_hijos_menores                        email  
0                  5     thomasgeorge@example.com  
1                  2         kbarrera@example.net  
2                  2     joshuawagner@example.com  
3                  2           wweber@example.net  
4                  0   ericksonsandra@example.com  
..               ...                          ...  
495                4    romanmargaret@example.com  
496                1  veronicajohnson@example.com  
497                2        liubrenda@example.net  
498                4          orivera@example.net  
499                5         steven49@example.net  

[500 rows x 8 columns]

In [33]:
df.dtypes

fecha_registro      datetime64[ns]
nombre                      object
sexo                         int32
fecha_nacimiento    datetime64[ns]
cp                           int64
n_hijos_menores              int64
email                       object
user_id                      int64
edad                         int64
dtype: object

In [3]:
# Convertimos la columna 'fecha_registro' a tipo datetime
df['fecha_registro'] = pd.to_datetime(df['fecha_registro'], format='%d-%m-%Y')

# De la columna de "Sexo"
df["sexo"][df["sexo"] == "M"] = 0 # mujer
df["sexo"][df["sexo"] == "H"] = 1 # hombre

# Cambio de tipo objet a tipo int
df["sexo"] = df["sexo"].astype(int)

# Convertimos la columna 'fecha_nacimiento' a tipo datetime
df['fecha_nacimiento'] = pd.to_datetime(df['fecha_nacimiento'], format='%d-%m-%Y')

# Calculamos la edad que tendrán hoy los usuarios
hoy = pd.to_datetime('today')
hoy

df['edad'] = hoy.year - df['fecha_nacimiento'].dt.year
df["edad"]

C:\Users\Blanca\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\Blanca\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


0       92
1       97
2       75
3       96
4       20
      ... 
495    101
496     59
497     78
498     27
499     31
Name: edad, Length: 500, dtype: int64

In [4]:
df 

fecha_registro             nombre  sexo fecha_nacimiento     cp  \
0       2023-06-27         Amy Hansen     1       1931-06-27  28012   
1       2023-06-19  Todd Hernandez MD     1       1926-03-13  28080   
2       2023-05-09     Leonard Rivera     0       1948-12-03  28035   
3       2023-05-17     Monica Sanchez     0       1927-08-09  28028   
4       2023-03-02       Travis Cross     0       2003-08-09  28013   
..             ...                ...   ...              ...    ...   
495     2023-07-03       Judith Short     1       1922-07-30  28038   
496     2023-03-12   Walter Lewis PhD     0       1964-07-02  28055   
497     2023-05-23        Tina Reeves     0       1945-09-27  28025   
498     2023-01-26        Bill Miller     1       1996-06-16  28026   
499     2023-04-26      Edwin Burgess     0       1992-04-22  28035   

     n_hijos_menores                         email  user_id  edad  
0                  3  kathleencardenas@example.net   106324    92  
1                  2             npace@example.com   776802    97  
2                  3         michael29@example.net   583556    75  
3                  3           sarah10@example.net   835648    96  
4                  2      shawnjackson@example.org   362284    20  
..               ...                           ...      ...   ...  
495                4     williamsjames@example.net   273400   101  
496                0     lindseygarcia@example.org   908240    59  
497                3         phillip51@example.net   950357    78  
498                1     aprilcampbell@example.net   446087    27  
499                3   hernandezashley@example.org   209294    31  

[500 rows x 9 columns]

In [5]:
# Selecting the desired columns from the original DataFrame
df2 = df[['sexo', 'cp', 'n_hijos_menores', 'edad', 'user_id']].copy()

# Display the new DataFrame df2
df2

sexo     cp  n_hijos_menores  edad  user_id
0       1  28012                3    92   106324
1       1  28080                2    97   776802
2       0  28035                3    75   583556
3       0  28028                3    96   835648
4       0  28013                2    20   362284
..    ...    ...              ...   ...      ...
495     1  28038                4   101   273400
496     0  28055                0    59   908240
497     0  28025                3    78   950357
498     1  28026                1    27   446087
499     0  28035                3    31   209294

[500 rows x 5 columns]

In [6]:
# Create a copy of 'df2' as 'df3'
df3 = df2.copy()

# Generate random values (0 or 1) for the new column 'Q_tot' in 'df3'
df3['Q_tot'] = [random.randint(0, 1) for _ in range(len(df3))]

# Display the new DataFrame df3
df3

sexo     cp  n_hijos_menores  edad  user_id  Q_tot
0       1  28012                3    92   106324      0
1       1  28080                2    97   776802      0
2       0  28035                3    75   583556      0
3       0  28028                3    96   835648      0
4       0  28013                2    20   362284      1
..    ...    ...              ...   ...      ...    ...
495     1  28038                4   101   273400      0
496     0  28055                0    59   908240      1
497     0  28025                3    78   950357      1
498     1  28026                1    27   446087      1
499     0  28035                3    31   209294      0

[500 rows x 6 columns]

In [13]:
# Get the count of each unique value in the 'Q_tot' column
df3['Q_tot'].value_counts()


0    256
1    244
Name: Q_tot, dtype: int64

In [14]:
df4 = df3.drop(columns="user_id")
df4

sexo     cp  n_hijos_menores  edad  Q_tot
0       1  28012                3    92      0
1       1  28080                2    97      0
2       0  28035                3    75      0
3       0  28028                3    96      0
4       0  28013                2    20      1
..    ...    ...              ...   ...    ...
495     1  28038                4   101      0
496     0  28055                0    59      1
497     0  28025                3    78      1
498     1  28026                1    27      1
499     0  28035                3    31      0

[500 rows x 5 columns]

In [15]:
X = df4.drop('Q_tot', axis=1)
y = df4['Q_tot']

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(400, 4)
(100, 4)
(400,)
(100,)


In [20]:
model = LogisticRegression(random_state=42)
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Calculate accuracy and other evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
classification_report_result = classification_report(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

# Display the results
print("Accuracy:", accuracy)
print("Classification Report:")
print(classification_report_result)
print("Confusion Matrix:")
print(confusion_mat)

Accuracy: 0.49
Classification Report:
              precision    recall  f1-score   support

           0       0.49      1.00      0.66        49
           1       0.00      0.00      0.00        51

    accuracy                           0.49       100
   macro avg       0.24      0.50      0.33       100
weighted avg       0.24      0.49      0.32       100

Confusion Matrix:
[[49  0]
 [51  0]]


c:\Users\Blanca\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Blanca\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Blanca\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average,

In [24]:
# Define the pipeline
pipeline = Pipeline([
    ('scaler', StandardScaler()),  # Preprocessing step: StandardScaler
    ('model', LogisticRegression())  # Best model: LogisticRegression
])

# Fit the pipeline to the training data
pipeline.fit(X_train, y_train)

# Make predictions on the test data
y_pred = pipeline.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.44


In [25]:
from sklearn.tree import DecisionTreeClassifier

In [26]:
# Create and fit the Decision Tree model with max_depth=3
model = DecisionTreeClassifier(max_depth=3, random_state=42)
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Calculate accuracy and other evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
classification_report_result = classification_report(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

# Display the results
print("Accuracy:", accuracy)
print("Classification Report:")
print(classification_report_result)
print("Confusion Matrix:")
print(confusion_mat)

Accuracy: 0.49
Classification Report:
              precision    recall  f1-score   support

           0       0.49      0.94      0.64        49
           1       0.50      0.06      0.11        51

    accuracy                           0.49       100
   macro avg       0.49      0.50      0.37       100
weighted avg       0.49      0.49      0.37       100

Confusion Matrix:
[[46  3]
 [48  3]]


In [27]:
from sklearn.ensemble import RandomForestClassifier

In [32]:
# Create and fit the Random Forest model
model = RandomForestClassifier(n_estimators=250, max_depth=3, random_state=42)
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Calculate accuracy and other evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
classification_report_result = classification_report(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

# Display the results
print("Accuracy:", accuracy)
print("Classification Report:")
print(classification_report_result)
print("Confusion Matrix:")
print(confusion_mat)

Accuracy: 0.51
Classification Report:
              precision    recall  f1-score   support

           0       0.50      0.73      0.60        49
           1       0.54      0.29      0.38        51

    accuracy                           0.51       100
   macro avg       0.52      0.51      0.49       100
weighted avg       0.52      0.51      0.49       100

Confusion Matrix:
[[36 13]
 [36 15]]
